export const countries = [
  { name: ' Afghanistan (+93)', dialCode: '+93', code: 'AF', flag: '🇦🇫' },
  { name: ' Albania (+355)', dialCode: '+355', code: 'AL', flag: '🇦🇱' },
  { name: ' Algeria (+213)', dialCode: '+213', code: 'DZ', flag: '🇩🇿' },
  { name: ' Andorra (+376)', dialCode: '+376', code: 'AD', flag: '🇦🇩' },
  { name: ' Angola (+244)', dialCode: '+244', code: 'AO', flag: '🇦🇴' },
  { name: ' Argentina (+54)', dialCode: '+54', code: 'AR', flag: '🇦🇷' },
  { name: ' Armenia (+374)', dialCode: '+374', code: 'AM', flag: '🇦🇲' },
  { name: ' Australia (+61)', dialCode: '+61', code: 'AU', flag: '🇦🇺' },
  { name: ' Austria (+43)', dialCode: '+43', code: 'AT', flag: '🇦🇹' },
  { name: ' Azerbaijan (+994)', dialCode: '+994', code: 'AZ', flag: '🇦🇿' },
  { name: ' Bahrain (+973)', dialCode: '+973', code: 'BH', flag: '🇧🇭' },
  { name: ' Bangladesh (+880)', dialCode: '+880', code: 'BD', flag: '🇧🇩' },
  { name: ' Belarus (+375)', dialCode: '+375', code: 'BY', flag: '🇧🇾' },
  { name: ' Belgium (+32)', dialCode: '+32', code: 'BE', flag: '🇧🇪' },
  { name: ' Brazil (+55)', dialCode: '+55', code: 'BR', flag: '🇧🇷' },
  { name: ' Canada (+1)', dialCode: '+1', code: 'CA', flag: '🇨🇦' },
  { name: ' China (+86)', dialCode: '+86', code: 'CN', flag: '🇨🇳' },
  { name: ' Colombia (+57)', dialCode: '+57', code: 'CO', flag: '🇨🇴' },
  { name: ' Denmark (+45)', dialCode: '+45', code: 'DK', flag: '🇩🇰' },
  { name: ' Egypt (+20)', dialCode: '+20', code: 'EG', flag: '🇪🇬' },
  { name: ' France (+33)', dialCode: '+33', code: 'FR', flag: '🇫🇷' },
  { name: 'Germany (+49)', dialCode: '+49', code: 'DE', flag: '🇩🇪' },
  { name: ' Greece (+30)', dialCode: '+30', code: 'GR', flag: '🇬🇷' },
  { name: ' Hong Kong (+852)', dialCode: '+852', code: 'HK', flag: '🇭🇰' },
  { name: ' India (+91)', dialCode: '+91', code: 'IN', flag: '🇮🇳' },
  { name: ' Indonesia (+62)', dialCode: '+62', code: 'ID', flag: '🇮🇩' },
  { name: ' Iran (+98)', dialCode: '+98', code: 'IR', flag: '🇮🇷' },
  { name: ' Iraq (+964)', dialCode: '+964', code: 'IQ', flag: '🇮🇶' },
  { name: ' Ireland (+353)', dialCode: '+353', code: 'IE', flag: '🇮🇪' },
  { name: ' Italy (+39)', dialCode: '+39', code: 'IT', flag: '🇮🇹' },
  { name: ' Japan (+81)', dialCode: '+81', code: 'JP', flag: '🇯🇵' },
  { name: ' Kenya (+254)', dialCode: '+254', code: 'KE', flag: '🇰🇪' },
  { name: ' Malaysia (+60)', dialCode: '+60', code: 'MY', flag: '🇲🇾' },
  { name: ' Mexico (+52)', dialCode: '+52', code: 'MX', flag: '🇲🇽' },
  { name: ' Nepal (+977)', dialCode: '+977', code: 'NP', flag: '🇳🇵' },
  { name: ' Netherlands (+31)', dialCode: '+31', code: 'NL', flag: '🇳🇱' },
  { name: ' New Zealand (+64)', dialCode: '+64', code: 'NZ', flag: '🇳🇿' },
  { name: ' Nigeria (+234)', dialCode: '+234', code: 'NG', flag: '🇳🇬' },
  { name: ' Norway (+47)', dialCode: '+47', code: 'NO', flag: '🇳🇴' },
  { name: ' Pakistan (+92)', dialCode: '+92', code: 'PK', flag: '🇵🇰' },
  { name: ' Philippines (+63)', dialCode: '+63', code: 'PH', flag: '🇵🇭' },
  { name: ' Poland (+48)', dialCode: '+48', code: 'PL', flag: '🇵🇱' },
  { name: ' Portugal (+351)', dialCode: '+351', code: 'PT', flag: '🇵🇹' },
  { name: ' Qatar (+974)', dialCode: '+974', code: 'QA', flag: '🇶🇦' },
  { name: ' Russia (+7)', dialCode: '+7', code: 'RU', flag: '🇷🇺' },
  { name: ' Saudi Arabia (+966)', dialCode: '+966', code: 'SA', flag: '🇸🇦' },
  { name: ' South Africa (+27)', dialCode: '+27', code: 'ZA', flag: '🇿🇦' },
  { name: ' South Korea (+82)', dialCode: '+82', code: 'KR', flag: '🇰🇷' },
  { name: ' Spain (+34)', dialCode: '+34', code: 'ES', flag: '🇪🇸' },
  { name: ' Sri Lanka (+94)', dialCode: '+94', code: 'LK', flag: '🇱🇰' },
  { name: ' Sweden (+46)', dialCode: '+46', code: 'SE', flag: '🇸🇪' },
  { name: ' Switzerland (+41)', dialCode: '+41', code: 'CH', flag: '🇨🇭' },
  { name: ' Thailand (+66)', dialCode: '+66', code: 'TH', flag: '🇹🇭' },
  { name: ' Turkey (+90)', dialCode: '+90', code: 'TR', flag: '🇹🇷' },
  {
    name: ' United Arab Emirates (+971)',
    dialCode: '+971',
    code: 'AE',
    flag: '🇦🇪',
  },
  { name: ' United Kingdom (+44)', dialCode: '+44', code: 'GB', flag: '🇬🇧' },
  { name: ' United States (+1)', dialCode: '+1', code: 'US', flag: '🇺🇸' },
  { name: ' Vietnam (+84)', dialCode: '+84', code: 'VN', flag: '🇻🇳' },
];

export default countries;
